# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Release
    generates:
      - ./build/CMakeCache.txt
    sources:
      - ./CMakeLists.txt
  build:
    cmds:
      - task: cmake
      - cmake --build build
  run:
    cmds:
      - task: build
      - ./build/Application_Main 
